# This workflow performs test builds across a diversity of supported platforms
#
#     - ubuntu-latest  - gcc
#     - ubuntu-latest  - clang
#     - ubuntu-24.04   - gcc   (For backwards compatablity)
#     - windows-latest - cl
#     - macos-latest   - clang
#
      

name: Multi-Platform Build Tests

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-latest
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-22.04
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Checkout full-depth to facilitate auto versioning
        fetch-depth: 0

    - name: Install optional dependencies (Ubuntu)
      if: startsWith( matrix.os, 'ubuntu-' )
      shell: bash
      run: |
        # install packages
        sudo apt-get update
        sudo apt-get -y install xvfb
        sudo apt-get -y install pkgconf libqrencode-dev
        sudo apt-get -y install barcode
        # install zint-2.15.0 from source
        wget https://downloads.sourceforge.net/project/zint/zint/2.15.0/zint-2.15.0-src.tar.gz && tar xzf zint-2.15.0-src.tar.gz && ( cd zint-2.15.0-src && mkdir build && cd build && cmake .. && make && sudo make install )

    - name: Pre-install vcpkg (Windows)
      if: startsWith( matrix.os, 'windows-' )
      shell: bash
      run: |
        git clone --depth 1 https://github.com/microsoft/vcpkg.git

    - name: Restore vcpkg cache (Windows)
      if: startsWith(matrix.os, 'windows-')
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/vcpkg/installed
          ${{ github.workspace }}/vcpkg/downloads
        key: vcpkg-${{ runner.os }}-${{ hashFiles('.github/workflows/build-tests.yml') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Install optional dependencies (Windows)
      if: startsWith( matrix.os, 'windows-' )
      shell: bash
      run: |
        # install packages
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install pkgconf
        ./vcpkg/vcpkg install zlib
        ./vcpkg/vcpkg install libqrencode
        ./vcpkg/vcpkg install zint
        echo "TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

    - name: Install optional dependencies (MacOS)
      if: startsWith( matrix.os, 'macos-' )
      shell: bash
      run: |
        # install packages
        brew install zlib
        brew install qrencode
        brew install zint

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.2.*'
        install-deps: 'true'
        archives: 'qtbase qtsvg qttools icu qttranslations qtwayland'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_TOOLCHAIN_FILE=${{ env.TOOLCHAIN_FILE }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test (Ubuntu)
      if: startsWith( matrix.os, 'ubuntu-' )
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        xvfb-run -a ./glabels/glabels-qt --Version
        xvfb-run -a ctest --build-config ${{ matrix.build_type }}

    - name: Test (Windows)
      if: startsWith( matrix.os, 'windows-' )
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        ctest --build-config ${{ matrix.build_type }}

    - name: Test (MacOS)
      if: startsWith( matrix.os, 'macos-' )
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        ./glabels/glabels-qt --Version
        ctest --build-config ${{ matrix.build_type }}

    - name: Install render test dependencies (Ubuntu-latest)
      if: startsWith( matrix.os, 'ubuntu-latest' )
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        sudo apt-get -y install xwayland-run
        sudo apt-get -y install comparepdf

    - name: Render tests (Ubuntu-latest)
      if: startsWith( matrix.os, 'ubuntu-latest' )
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: bash
      env:
        TEST_DIR: ${{ github.workspace }}/test-data
      run: |
        run-x() { xvfb-run -a "$@"; }
        run-w() { wlheadless-run -c weston --log=/dev/null -- "$@"; }
        #
        #
        echo "----------------------- X ----------------------------"
        run-x fc-list : family
        echo "----------------------- W ----------------------------"
        run-w fc-list : family
        echo "------------------------------------------------------"
        echo "================"
        echo "X11 render tests"
        echo "================"
        run-x ./glabels-batch/glabels-batch-qt --Version
        #
        echo "simple-shapes.glabels"
        echo "---------------------"
        run-x ./glabels-batch/glabels-batch-qt -o simple-shapes-x.pdf "$TEST_DIR/simple-shapes.glabels"
        comparepdf -ca -v2 "$TEST_DIR/simple-shapes.pdf" simple-shapes-x.pdf
        #
        echo "simple-code39.glabels"
        echo "---------------------"
        run-x ./glabels-batch/glabels-batch-qt -o simple-code39-x.pdf "$TEST_DIR/simple-code39.glabels"
        comparepdf -ca -v2 "$TEST_DIR/simple-code39.pdf" simple-code39-x.pdf
        #
        echo "simple-text-noto-sans.glabels"
        echo "---------------------"
        run-x ./glabels-batch/glabels-batch-qt -o simple-text-noto-sans-x.pdf "$TEST_DIR/simple-text-noto-sans.glabels"
        comparepdf -ca -v2 "$TEST_DIR/simple-text-noto-sans.pdf" simple-text-noto-sans-x.pdf
        #
        #
        echo "===================="
        echo "Wayland render tests"
        echo "===================="
        run-w ./glabels-batch/glabels-batch-qt --Version
        #
        echo "simple-shapes.glabels"
        echo "---------------------"
        run-w ./glabels-batch/glabels-batch-qt -o simple-shapes-w.pdf "$TEST_DIR/simple-shapes.glabels"
        comparepdf -ca -v2 "$TEST_DIR/simple-shapes.pdf" simple-shapes-w.pdf
        #
        echo "simple-code39.glabels"
        echo "---------------------"
        run-w ./glabels-batch/glabels-batch-qt -o simple-code39-w.pdf "$TEST_DIR/simple-code39.glabels"
        comparepdf -ca -v2 "$TEST_DIR/simple-code39.pdf" simple-code39-w.pdf
        #
        echo "simple-text-noto-sans.glabels"
        echo "---------------------"
        run-w ./glabels-batch/glabels-batch-qt -o simple-text-noto-sans-w.pdf "$TEST_DIR/simple-text-noto-sans.glabels"
        comparepdf -ca -v2 "$TEST_DIR/simple-text-noto-sans.pdf" simple-text-noto-sans-w.pdf


#    - name: Tmate
#      uses: mxschmitt/action-tmate@v3
#      if: failure()

